baseURL = 'https://thedeveloperpost.com/'
languageCode = 'en-us'
title = 'The Developer Post'

[assets]
disableHLJS = true

[markup.highlight]
codeFences = true
guessSyntax = false
lineNos = true
noClasses = true
style = "dracula"


[taxonomies]
    tag = "tags"
    category = "categories"